development:
  adapter: postgresql
  encoding: unicode
  database: world_cup_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: world_cup_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: world_cup_prod
  pool: 5
