development:
  adapter: postgresql
  encoding: unicode
  database: world_cup_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: world_cup_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  # database: <%= ENV['DATABASE_NAME'] %>
  # user: <%= ENV['DATABASE_USER'] || 'postgres' %>
  # host:  <%= ENV['DATABASE_HOST'] %>
  # password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: <%= ENV['DB_POOL'] || 15 %>
